#暂时不考虑多实例服务,thrift server config
server:
    port: 8090
thrift:
  server:
    host: 127.0.0.1
    port: 8094
    timeout: 60000 # 超时时间
    maxIdle: 3 #最大空闲连接数,默认值 8
    maxTotal: 10 #最大连接数, 默认值 8
    minIdle: 3 #最小空闲连接数, 默认值 0

